name: telnet
description: Telnet client implemented in dart language. Supports text transmission and negotiate options.
version: 1.0.7
homepage: https://github.com/YowFung/telnet
verified_publishers: pub.yowfung.cn

environment:
  sdk: '>=2.14.0 <3.0.0'


dev_dependencies:
  lints: ^1.0.1
  test: ^1.21.0
