name: telnet
description: Telnet client implemented in dart language.
version: 1.0.2
homepage: https://github.com/YowFung/telnet
verified_publishers: yowfung

environment:
  sdk: '>=2.14.0 <3.0.0'


dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
